# Generated by Django 2.2.1 on 2021-02-12 15:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_auto_20201210_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_profile',
            new_name='eval_profile',
        ),
    ]
