# Generated by Django 2.2.1 on 2021-02-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210212_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Upload',
            field=models.FileField(max_length=256, null=True, upload_to='media/'),
        ),
    ]
