# Generated by Django 2.1.1 on 2022-02-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_facultyadvisor_fields_upload_your_reference_commitment_letter_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_details',
            name='created_at',
            field=models.DateField(blank=True, default='2022-02-07'),
        ),
    ]
